-- ============================================================
-- FINANCIAL ANALYTICS DASHBOARD
-- DAX MEASURES
-- ============================================================

-- ============================================================
-- 1. TOTAL RECORDS
-- ============================================================

Total Records =
COUNTROWS(FinancialData)

-- ============================================================
-- 2. AVERAGE GROWTH
-- ============================================================

Average Growth =
AVERAGE(FinancialData[GrowthRate])


-- ============================================================
-- 3. MAXIMUM GROWTH
-- ============================================================

Maximum Growth =
MAX(FinancialData[GrowthRate])

-- ============================================================
-- 4. MINIMUM GROWTH
-- ============================================================

Minimum Growth =
MIN(FinancialData[GrowthRate])

-- ============================================================
-- 5. POSITIVE GROWTH RECORDS
-- ============================================================

Positive Growth Records =
CALCULATE(
    COUNTROWS(FinancialData),
    FinancialData[GrowthRate] >= 0
)

-- ============================================================
-- 6. NEGATIVE GROWTH RECORDS
-- ============================================================

Negative Growth Records =
CALCULATE(
    COUNTROWS(FinancialData),
    FinancialData[GrowthRate] < 0
)

-- ============================================================
-- 7. POSITIVE GROWTH %
-- ============================================================

Positive Growth % =
DIVIDE(
    [Positive Growth Records],
    [Total Records],
    0
)

-- ============================================================
-- 8. NEGATIVE GROWTH %
-- ============================================================

Negative Growth % =
DIVIDE(
    [Negative Growth Records],
    [Total Records],
    0
)
